Fix Makefile which breaks under git-buildpackage
It appears $PWD cannot be relied upon. git-buildpackage is probably santizing
the environment and or changing directories.

The error was:

  ls: cannot access /drivers/gud/mobicore_driver/platforms: No such file or directory
  ...
  In file included from drivers/gud/mobicore_driver/logging.c:16:
  drivers/gud/mobicore_driver/mc_drv_module.h:25:22: error: platform.h: No such file or directory